<table id="encabezadodelogados">
    <tr>
        <td rowspan="2" colspan="2">
            <b>
                Matriz de requisitos legales derogados
            </b>
        </td>
        <td colspan="2">
            <b>
                Codigo:
            </b>
        </td>
        <td>
            0000
        </td>
        <td>
            <b>
                Versi&oacute;n:
            </b>
        </td>
        <td>
            1
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <b>
                Fecha:
            </b>
        </td>
        <td colspan="2">
            2016-09-01
        </td>
    </tr>
    <tr>
        <td colspan="2" rowspan="2">
            <b>
                Elaborado por:
            </b>
        </td>
        <td colspan="2" rowspan="2">
            <?php
                echo $_SESSION['nombre'];
            ?>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <b>
                Fecha de elaboraci&oacute;n:
            </b>
        </td>
        <td colspan="2">
            <?php
                echo $arraFecha[0];
            ?>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <b>
                Fecha de actualizaci&oacute;n:
            </b>
        </td>
        <td colspan="2">
            <?php
                echo $arraFecha[0];
            ?>
        </td>
    </tr>
</table>