<center>
    <nav>
        <ul class="fancyNav">
            <li>
                <a href="inicio.php" class="homeIcon">
                    Home
                </a>
            </li>
            <li>
                <a href="empresa.php">
                    Empresas
                </a>
            </li>
            <li>
                <a href="usuario.php">
                    Usuario
                </a>
            </li>
            <li>
                <a href="cerrar.php">
                    Salir
                </a>
            </li>
        </ul>
    </nav>
</center>