<center>
    <nav>
        <ul class="fancyNav">
            <li>
                <a href="inicio.php" class="backIcon">
                    Home
                </a>
            </li>
            <li>
                <a href="crearUsuario.php">
                    Crear nueva usuario
                </a>
            </li>
            <li>
                <a href="listaModificarUsuario.php">
                    Modificar usuario
                </a>
            </li>
            <li>
                <a href="eliminarUsuario.php">
                    Eliminar usuario
                </a>
            </li>
            <li>
                <a href="listarUsuarios.php">
                    Listado de usuarios
                </a>
            </li>
        </ul>
    </nav>
</center>