<center>
    <nav>
        <ul class="fancyNav">
            <li>
                <a href="inicio.php" class="backIcon">
                    Home
                </a>
            </li>
            <li>
                <a href="verEmpresas.php">
                    Ver empresas
                </a>
            </li>
            <li>
                <a href="reactivarEmpresa.php">
                    Re-activar empresa
                </a>
            </li>
            <li>
                <a href="crearEmpresa.php">
                    Crear nueva empresa
                </a>
            </li>
            <li>
                <a href="listaModificarEmpresa.php">
                    Modificar informaci&oacute;n de empresa
                </a>
            </li>
        </ul>
    </nav>
</center>